version: "3.6"
services:
  database:
    environment:
      POSTGRES_DB: ddev
      POSTGRES_PASSWORD_FILE: /ddev/secrets/postgres-password
    image: ${dockerID}/ddev_db
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres-password
    volumes:
    - postgres-data:/var/lib/postgresql/data
  api:
    image: ${dockerID}/api:prod
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres_password
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    ports:
    - "8080:8080"
    env_file:
    - env-prod.conf
  ui:
    image: ${dockerID}/ddev_ui
    ports:
    - "3000:3000"
volumes:
  postgres-data: {}
secrets:
  postgres-password:
    external: true
